version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: url-shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8888
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8181:8181
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url-shortener
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 8888
    depends_on:
      - postgres

volumes:
  postgres_data:
